    let masterGalleryData = [];

    // 1. Fetch and Parse CSV File
    Papa.parse("images.csv", {
        download: true,
        header: true,
        skipEmptyLines: true,
        complete: function(results) {
            masterGalleryData = results.data;
            populateFilterDropdowns(masterGalleryData);
            displayGallery(masterGalleryData);
        },
        error: function(err) {
            document.getElementById('portfolio-grid').innerHTML = '<p class="no-results">Error loading portfolio data. Please ensure images.csv exists.</p>';
            console.error(err);
        }
    });

    // 2. Dynamically extract unique values for dropdown filters (Matches lowercase CSV headers)
    function populateFilterDropdowns(data) {
        const attributes = ['subject', 'medium', 'location', 'size', 'artist'];
        attributes.forEach(attr => {
            const selectElement = document.getElementById(`filter-${attr}`);
            
            // Extract unique values matching exact lowercase CSV headers safely
            const uniqueValues = [...new Set(data.map(item => {
                const val = item[attr];
                return val ? val.trim() : null;
            }).filter(Boolean))].sort();
            
            // Clear any existing dynamic options except the first "All" option
            while (selectElement.options.length > 1) {
                selectElement.remove(1);
            }

            uniqueValues.forEach(value => {
                const option = document.createElement('option');
                option.value = value;
                option.textContent = value;
                selectElement.appendChild(option);
            });
        });
    }

    // 3. Render gallery grid cards
    function displayGallery(items) {
        const grid = document.getElementById('portfolio-grid');
        grid.innerHTML = '';
        
        if (items.length === 0) {
            grid.innerHTML = '<div class="no-results">No items match your chosen filter criteria.</div>';
            return;
        }
        
        items.forEach((item, index) => {
            // Guard clause to prevent script crash if a row structure is corrupt
            if (!item.filename) return;

            const card = document.createElement('div');
            card.className = 'gallery-card';
            
            let cleanFilename = item.filename.trim();
            // Since your CSV explicitly includes "imgfiles/ecs-art/", we just append standard relative prefix "./"
            let imgPath = cleanFilename.startsWith('imgfiles/') ? `./${cleanFilename}` : `./imgfiles/ecs-art/${cleanFilename}`;

            card.innerHTML = `
                <img src="${imgPath}" alt="${item.subject || 'Artwork'}" loading="lazy">
                <div class="gallery-info">
                    <h3>${item.subject || 'Untitled'}</h3>
                    <p><strong>Medium:</strong> ${item.medium || 'N/A'}</p>
                    <p><strong>Location:</strong> ${item.location || 'N/A'}</p>
                    <p><strong>Size:</strong> ${item.size || 'N/A'}</p>
                </div>
            `;
            
            // Pass the verified explicit path straight to the lightbox
            card.addEventListener('click', () => openLightbox(item, imgPath));
            grid.appendChild(card);
        });
    }

    // 4. Filter gallery calculation (Strict lowercase column matches)
    function filterGallery() {
        const subjectFilter = document.getElementById('filter-subject').value;
        const mediumFilter = document.getElementById('filter-medium').value;
        const locationFilter = document.getElementById('filter-location').value;
        const sizeFilter = document.getElementById('filter-size').value;
        const artistFilter = document.getElementById('filter-artist').value;
        
        const filteredResults = masterGalleryData.filter(item => {
            const matchSubject = (subjectFilter === 'all' || item.subject?.trim() === subjectFilter);
            const matchMedium = (mediumFilter === 'all' || item.medium?.trim() === mediumFilter);
            const matchLocation = (locationFilter === 'all' || item.location?.trim() === locationFilter);
            const matchCategory = (sizeFilter === 'all' || item.size?.trim() === sizeFilter);
            const matchArtist = (artistFilter === 'all' || item.artist?.trim() === artistFilter);
            return matchSubject && matchMedium && matchLocation && matchSize && matchArtist;
        });
        displayGallery(filteredResults);
    }

    // --- LIGHTBOX INTERACTION FUNCTIONS ---

    function openLightbox(item, calculatedPath) {
        // Uses the direct path generated by the card loop
        const imgPath = calculatedPath || `./${item.filename.trim()}`;
        
        document.getElementById('lightbox-img').src = imgPath;
        document.getElementById('lightbox-img').alt = item.subject || 'Artwork';
        document.getElementById('lightbox-title').textContent = item.subject || 'Untitled';
        document.getElementById('lightbox-medium').textContent = item.medium || 'N/A';
        document.getElementById('lightbox-location').textContent = item.location || 'N/A';
        document.getElementById('lightbox-size').textContent = item.size || 'N/A';
        document.getElementById('lightbox-artist').textContent = item.artist || 'N/A';
        
        document.getElementById('lightbox').style.display = 'flex';
        document.body.style.overflow = 'hidden';
    }

    function closeLightbox(event) {
        if (event && event.stopPropagation) {
            event.stopPropagation();
        }
        document.getElementById('lightbox').style.display = 'none';
        document.body.style.overflow = 'auto';
    }

    window.addEventListener('keydown', function(event) {
        if (event.key === 'Escape') {
            closeLightbox();
        }
    });
